DEB [20181222-12:46:36.624] thr=1   paramiko.transport: starting thread (server mode): 0x4119cc50L
DEB [20181222-12:46:36.626] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
DEB [20181222-12:46:36.628] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-PuTTY_Release_0.70
INF [20181222-12:46:36.628] thr=1   paramiko.transport: Connected (version 2.0, client PuTTY_Release_0.70)
DEB [20181222-12:46:36.629] thr=1   paramiko.transport: kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'rsa2048-sha256', u'rsa1024-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-ed25519', u'ecdsa-sha2-nistp256', u'ecdsa-sha2-nistp384', u'ecdsa-sha2-nistp521', u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes256-ctr', u'aes256-cbc', u'rijndael-cbc@lysator.liu.se', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'chacha20-poly1305@openssh.com', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc', u'arcfour256', u'arcfour128'] server encrypt:[u'aes256-ctr', u'aes256-cbc', u'rijndael-cbc@lysator.liu.se', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'chacha20-poly1305@openssh.com', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc', u'arcfour256', u'arcfour128'] client mac:[u'hmac-sha2-256', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-etm@openssh.com'] server mac:[u'hmac-sha2-256', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-etm@openssh.com'] client compress:[u'none', u'zlib'] server compress:[u'none', u'zlib'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181222-12:46:36.630] thr=1   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20181222-12:46:36.630] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20181222-12:46:36.630] thr=1   paramiko.transport: Cipher agreed: aes256-ctr
DEB [20181222-12:46:36.631] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20181222-12:46:36.631] thr=1   paramiko.transport: Compression agreed: none
DEB [20181222-12:46:36.636] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20181222-12:46:39.147] thr=1   paramiko.transport: Switch to new keys ...
DEB [20181222-12:46:41.296] thr=1   paramiko.transport: Auth request (type=none) service=ssh-connection, username=root
INF [20181222-12:46:41.296] thr=1   paramiko.transport: Auth rejected (none).
DEB [20181222-12:46:43.100] thr=1   paramiko.transport: Auth request (type=password) service=ssh-connection, username=root
INF [20181222-12:46:43.101] thr=1   paramiko.transport: Auth rejected (password).
DEB [20181222-12:46:57.473] thr=1   paramiko.transport: EOF in transport thread
DEB [20181223-00:33:48.172] thr=1   paramiko.transport: starting thread (server mode): 0x81dc0cd0L
DEB [20181223-00:33:48.173] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.2
ERR [20181223-00:33:53.906] thr=1   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20181223-00:33:53.908] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20181223-00:33:53.908] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-00:33:53.908] thr=1   paramiko.transport:     self._check_banner()
ERR [20181223-00:33:53.908] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2143, in _check_banner
ERR [20181223-00:33:53.908] thr=1   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20181223-00:33:53.908] thr=1   paramiko.transport: SSHException: Error reading SSH protocol banner
ERR [20181223-00:33:53.908] thr=1   paramiko.transport: 
DEB [20181223-00:36:43.050] thr=1   paramiko.transport: starting thread (server mode): 0xf562dcd0L
DEB [20181223-00:36:43.050] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-00:36:45.555] thr=1   paramiko.transport: Banner: 
ERR [20181223-00:36:47.603] thr=1   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20181223-00:36:47.604] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20181223-00:36:47.604] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-00:36:47.604] thr=1   paramiko.transport:     self._check_banner()
ERR [20181223-00:36:47.604] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2143, in _check_banner
ERR [20181223-00:36:47.604] thr=1   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20181223-00:36:47.604] thr=1   paramiko.transport: SSHException: Error reading SSH protocol banner
ERR [20181223-00:36:47.604] thr=1   paramiko.transport: 
DEB [20181223-00:36:59.374] thr=2   paramiko.transport: starting thread (server mode): 0xf562b0d0L
DEB [20181223-00:36:59.374] thr=2   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
ERR [20181223-00:37:00.703] thr=2   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20181223-00:37:00.703] thr=2   paramiko.transport: Traceback (most recent call last):
ERR [20181223-00:37:00.703] thr=2   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-00:37:00.703] thr=2   paramiko.transport:     self._check_banner()
ERR [20181223-00:37:00.703] thr=2   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2143, in _check_banner
ERR [20181223-00:37:00.703] thr=2   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20181223-00:37:00.703] thr=2   paramiko.transport: SSHException: Error reading SSH protocol banner
ERR [20181223-00:37:00.703] thr=2   paramiko.transport: 
DEB [20181223-01:42:37.305] thr=1   paramiko.transport: starting thread (server mode): 0xed4fccd0L
DEB [20181223-01:42:37.310] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
ERR [20181223-01:42:37.310] thr=1   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20181223-01:42:37.310] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.311] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-01:42:37.311] thr=1   paramiko.transport:     self._check_banner()
ERR [20181223-01:42:37.311] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2143, in _check_banner
ERR [20181223-01:42:37.311] thr=1   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20181223-01:42:37.311] thr=1   paramiko.transport: SSHException: Error reading SSH protocol banner
ERR [20181223-01:42:37.311] thr=1   paramiko.transport: 
DEB [20181223-01:42:37.311] thr=2   paramiko.transport: starting thread (server mode): 0xec4b5250L
DEB [20181223-01:42:37.312] thr=2   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.312] thr=3   paramiko.transport: starting thread (server mode): 0xed4fa0d0L
DEB [20181223-01:42:37.312] thr=3   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.313] thr=2   paramiko.transport: Remote version/idstring: SSH-1.5-Nmap-SSH1-Hostkey
ERR [20181223-01:42:37.313] thr=2   paramiko.transport: Exception: Incompatible version (1.5 instead of 2.0)
ERR [20181223-01:42:37.313] thr=2   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.313] thr=2   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-01:42:37.313] thr=2   paramiko.transport:     self._check_banner()
ERR [20181223-01:42:37.313] thr=2   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2167, in _check_banner
ERR [20181223-01:42:37.313] thr=2   paramiko.transport:     raise SSHException(msg.format(version))
ERR [20181223-01:42:37.313] thr=2   paramiko.transport: SSHException: Incompatible version (1.5 instead of 2.0)
ERR [20181223-01:42:37.313] thr=2   paramiko.transport: 
DEB [20181223-01:42:37.314] thr=3   paramiko.transport: Remote version/idstring: SSH-1.5-NmapNSE_1.0
ERR [20181223-01:42:37.314] thr=3   paramiko.transport: Exception: Incompatible version (1.5 instead of 2.0)
ERR [20181223-01:42:37.314] thr=3   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.314] thr=3   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181223-01:42:37.314] thr=3   paramiko.transport:     self._check_banner()
ERR [20181223-01:42:37.314] thr=3   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2167, in _check_banner
ERR [20181223-01:42:37.314] thr=3   paramiko.transport:     raise SSHException(msg.format(version))
ERR [20181223-01:42:37.314] thr=3   paramiko.transport: SSHException: Incompatible version (1.5 instead of 2.0)
ERR [20181223-01:42:37.314] thr=3   paramiko.transport: 
DEB [20181223-01:42:37.314] thr=4   paramiko.transport: starting thread (server mode): 0xec4b5490L
DEB [20181223-01:42:37.315] thr=4   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.315] thr=4   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.315] thr=4   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.316] thr=4   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ssh-dss'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.316] thr=4   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
ERR [20181223-01:42:37.316] thr=4   paramiko.transport: Exception: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.316] thr=4   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2010, in run
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2125, in _negotiate_keys
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:     self._parse_kex_init(m)
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2305, in _parse_kex_init
ERR [20181223-01:42:37.316] thr=4   paramiko.transport:     "Incompatible ssh peer (no acceptable host key)"
ERR [20181223-01:42:37.316] thr=4   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.316] thr=4   paramiko.transport: 
DEB [20181223-01:42:37.317] thr=5   paramiko.transport: starting thread (server mode): 0xed4fa190L
DEB [20181223-01:42:37.317] thr=5   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.317] thr=5   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.317] thr=5   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.318] thr=5   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.318] thr=5   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
DEB [20181223-01:42:37.318] thr=5   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20181223-01:42:37.319] thr=5   paramiko.transport: Cipher agreed: aes128-cbc
DEB [20181223-01:42:37.319] thr=5   paramiko.transport: MAC agreed: hmac-md5
DEB [20181223-01:42:37.319] thr=5   paramiko.transport: Compression agreed: none
DEB [20181223-01:42:37.328] thr=5   paramiko.transport: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEB [20181223-01:42:37.330] thr=5   paramiko.transport: EOF in transport thread
DEB [20181223-01:42:37.330] thr=6   paramiko.transport: starting thread (server mode): 0xec4b5d90L
DEB [20181223-01:42:37.330] thr=6   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.330] thr=6   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.330] thr=6   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.331] thr=6   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.331] thr=6   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
ERR [20181223-01:42:37.331] thr=6   paramiko.transport: Exception: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.331] thr=6   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.331] thr=6   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2010, in run
ERR [20181223-01:42:37.331] thr=6   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20181223-01:42:37.332] thr=6   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2125, in _negotiate_keys
ERR [20181223-01:42:37.332] thr=6   paramiko.transport:     self._parse_kex_init(m)
ERR [20181223-01:42:37.332] thr=6   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2305, in _parse_kex_init
ERR [20181223-01:42:37.332] thr=6   paramiko.transport:     "Incompatible ssh peer (no acceptable host key)"
ERR [20181223-01:42:37.332] thr=6   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.332] thr=6   paramiko.transport: 
DEB [20181223-01:42:37.332] thr=7   paramiko.transport: starting thread (server mode): 0xec4ce390L
DEB [20181223-01:42:37.332] thr=7   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.332] thr=7   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.332] thr=7   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.333] thr=7   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ecdsa-sha2-nistp384'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.333] thr=7   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
ERR [20181223-01:42:37.334] thr=7   paramiko.transport: Exception: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.334] thr=7   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2010, in run
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2125, in _negotiate_keys
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:     self._parse_kex_init(m)
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2305, in _parse_kex_init
ERR [20181223-01:42:37.334] thr=7   paramiko.transport:     "Incompatible ssh peer (no acceptable host key)"
ERR [20181223-01:42:37.334] thr=7   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.334] thr=7   paramiko.transport: 
DEB [20181223-01:42:37.335] thr=8   paramiko.transport: starting thread (server mode): 0xec4cead0L
DEB [20181223-01:42:37.335] thr=8   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.335] thr=8   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.335] thr=8   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.336] thr=8   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ecdsa-sha2-nistp521'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.336] thr=8   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
ERR [20181223-01:42:37.336] thr=8   paramiko.transport: Exception: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.336] thr=8   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2010, in run
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2125, in _negotiate_keys
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:     self._parse_kex_init(m)
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2305, in _parse_kex_init
ERR [20181223-01:42:37.337] thr=8   paramiko.transport:     "Incompatible ssh peer (no acceptable host key)"
ERR [20181223-01:42:37.337] thr=8   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.337] thr=8   paramiko.transport: 
DEB [20181223-01:42:37.337] thr=9   paramiko.transport: starting thread (server mode): 0xec4b5390L
DEB [20181223-01:42:37.338] thr=9   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
DEB [20181223-01:42:37.338] thr=9   paramiko.transport: Remote version/idstring: SSH-2.0-Nmap-SSH2-Hostkey
INF [20181223-01:42:37.338] thr=9   paramiko.transport: Connected (version 2.0, client Nmap-SSH2-Hostkey)
DEB [20181223-01:42:37.345] thr=9   paramiko.transport: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group-exchange-sha256'] server key:[u'ssh-ed25519'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20181223-01:42:37.345] thr=9   paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
ERR [20181223-01:42:37.345] thr=9   paramiko.transport: Exception: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.345] thr=9   paramiko.transport: Traceback (most recent call last):
ERR [20181223-01:42:37.345] thr=9   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2010, in run
ERR [20181223-01:42:37.346] thr=9   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20181223-01:42:37.346] thr=9   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2125, in _negotiate_keys
ERR [20181223-01:42:37.346] thr=9   paramiko.transport:     self._parse_kex_init(m)
ERR [20181223-01:42:37.346] thr=9   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2305, in _parse_kex_init
ERR [20181223-01:42:37.346] thr=9   paramiko.transport:     "Incompatible ssh peer (no acceptable host key)"
ERR [20181223-01:42:37.346] thr=9   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable host key)
ERR [20181223-01:42:37.346] thr=9   paramiko.transport: 
DEB [20181227-23:12:46.632] thr=1   paramiko.transport: starting thread (server mode): 0x398ebc90L
DEB [20181227-23:12:46.633] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-OpenSSH_4.6 Debian-4
ERR [20181227-23:12:46.634] thr=1   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20181227-23:12:46.637] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20181227-23:12:46.637] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1966, in run
ERR [20181227-23:12:46.637] thr=1   paramiko.transport:     self._check_banner()
ERR [20181227-23:12:46.637] thr=1   paramiko.transport:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2143, in _check_banner
ERR [20181227-23:12:46.637] thr=1   paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERR [20181227-23:12:46.637] thr=1   paramiko.transport: SSHException: Error reading SSH protocol banner
ERR [20181227-23:12:46.637] thr=1   paramiko.transport: 
